### ISSUE TITLE
Chore: set ESLint, Husky, Vercel Deployment

### ISSUE THREAD

**Issue by givvemee** [givvemee/colours#3]
# FEATURE

## Summary

> 이슈 요약

## To-Do

- [ ] set ESLint rules and typescript configurations
- [ ] set Husky and pre-commit
- [ ] Deployment setting thru vercel 

## ETC

> 기타 사항
