### ISSUE TITLE
Feature: Create a component where user can generate hex colour code in random

### ISSUE THREAD

**Issue by givvemee** [givvemee/colours#5]
# FEATURE

## Summary

> 이슈 요약

## To-Do

- [ ] the colour code generator should works with button click 
- [ ] the colour code should be generated randomly every single time
- [ ] there should not be hex colour code only but rgb code also 
- [ ] once the colour code is generated, the user can check it in so called preview component 
- [ ] TBD .. 

## ETC

> 기타 사항
