### ISSUE TITLE
Feature: Store generated code 

### ISSUE THREAD

**Issue by givvemee** [givvemee/colours#6]
# FEATURE
When the user once generated the colour code, it should be stored in a storage and also be reset.

## Summary

> 이슈 요약

## To-Do

- [ ] Check the usage for local storage, session storage and cookie
- [ ] the storage can carry maximum 3 (or 5) recent colour codes 
- [ ] there should be a button to reset the storage
- [ ] when the user tries to add one more code than its capacity on storage an warning alert needs to be appeared
- [ ] TBD 

## ETC

> 기타 사항
